#ifndef AMOAMO_DEFINITION_H
#define AMOAMO_DEFINITION_H

#include "cocos2d.h"

#define AMOAMO_PLATFORM_IS_IOS             (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
#define AMOAMO_PLATFORM_IS_ANDROID         (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)

#endif /* AMOAMO_DEFINITION_H */
